language: php

sudo: false

php:
    - 7.1
    - 7.2

cache:
    directories:
        - $HOME/.composer/cache

env: TMPDIR=/tmp

install:
    - phpenv config-rm xdebug.ini || true
    - travis_retry composer install --no-interaction --prefer-dist

    - mysql -e 'create database zftest;'
    - psql -c 'create database zftest;' -U postgres

    - cp ./tests/TestConfiguration.travis.php ./tests/TestConfiguration.php

script:
    - cd tests/
    - php runalltests.php

notifications:
    email: false
